const cardsArray = [
  { id: 1, color: 'red', isVisible: false, hasEqualColor: false },
  { id: 2, color: 'red', isVisible: false, hasEqualColor: false },
  { id: 3, color: 'green', isVisible: false, hasEqualColor: false },
  { id: 4, color: 'green', isVisible: false, hasEqualColor: false },
  { id: 5, color: 'blue', isVisible: false, hasEqualColor: false },
  { id: 6, color: 'blue', isVisible: false, hasEqualColor: false },
  { id: 7, color: 'coral', isVisible: false, hasEqualColor: false },
  { id: 8, color: 'coral', isVisible: false, hasEqualColor: false },
  { id: 9, color: 'purple', isVisible: false, hasEqualColor: false },
  { id: 10, color: 'purple', isVisible: false, hasEqualColor: false },
  { id: 11, color: 'yellow', isVisible: false, hasEqualColor: false },
  { id: 12, color: 'yellow', isVisible: false, hasEqualColor: false },
  { id: 13, color: 'brown', isVisible: false, hasEqualColor: false },
  { id: 14, color: 'brown', isVisible: false, hasEqualColor: false },
  { id: 15, color: 'aqua', isVisible: false, hasEqualColor: false },
  { id: 16, color: 'aqua', isVisible: false, hasEqualColor: false },
  { id: 17, color: 'pink', isVisible: false, hasEqualColor: false },
  { id: 18, color: 'pink', isVisible: false, hasEqualColor: false },
  { id: 19, color: 'grey', isVisible: false, hasEqualColor: false },
  { id: 20, color: 'grey', isVisible: false, hasEqualColor: false },
  { id: 21, color: 'lilac', isVisible: false, hasEqualColor: false },
  { id: 22, color: 'lilac', isVisible: false, hasEqualColor: false },
  { id: 23, color: 'lime', isVisible: false, hasEqualColor: false },
  { id: 24, color: 'lime', isVisible: false, hasEqualColor: false },
  { id: 25, color: 'fuchsia', isVisible: false, hasEqualColor: false },
  { id: 26, color: 'fuchsia', isVisible: false, hasEqualColor: false },
  { id: 27, color: 'egyptian blue', isVisible: false, hasEqualColor: false },
  { id: 28, color: 'egyptian blue', isVisible: false, hasEqualColor: false },
  { id: 29, color: 'celeste', isVisible: false, hasEqualColor: false },
  { id: 30, color: 'celeste', isVisible: false, hasEqualColor: false },
  { id: 31, color: 'beige', isVisible: false, hasEqualColor: false },
  { id: 32, color: 'beige', isVisible: false, hasEqualColor: false },
  { id: 33, color: 'army green', isVisible: false, hasEqualColor: false },
  { id: 34, color: 'army green', isVisible: false, hasEqualColor: false },
  { id: 35, color: 'amber', isVisible: false, hasEqualColor: false },
  { id: 36, color: 'amber', isVisible: false, hasEqualColor: false },
];

export default cardsArray;
